### ISSUE TITLE
Vite plugin for optimization

### ISSUE THREAD

**Issue by david-plugge** [lucide-icons/lucide#1944]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [X] all JS packages
- [ ] site

### Description

While the new way of importing components in svelte using the full path works pretty well to avoid annoyingly long vite optimizations, i think its just bad DX. So after a bit of playing around i came up with a vite plugin that solves this issue.

```ts
function lucideSvelteImportOptimizer(): Plugin {
	return {
		name: 'lucide-svelte optimizer',
		transform(code, id) {
			const ms = new MagicString(code, { filename: id });

			ms.replace(
				/([ \t]*)import\s+\{(.*?)\}\s+from\s+['"]lucide-svelte['"];?/g,
				(match, whitespace: string, importNames: string) => {
					const hasSemi = match.endsWith(';');

					const imports = importNames
						.split(',')
						.map((v) => v.trim())
						.map((name) => {
							const path = name
								.split('')
								.map((c, i) => {
									const code = c.charCodeAt(0);
									return code >= 65 && code <= 90
										? (i === 0 ? '' : '-') + c.toLowerCase()
										: c;
								})
								.join('');

							return `${whitespace}import ${name} from 'lucide-svelte/icons/${path}'${hasSemi ? ';' : ''}`;
						});

					return imports.join('\n');
				},
			);

			if (ms.hasChanged()) {
				return {
					code: ms.toString(),
					map: ms.generateMap(),
				};
			}
		},
	};
}
```

I did not yet test if it works with aliases (eg. `User as UserIcon`) with other than that it works pretty well!

### Use cases

```svelte
<script>
  import { User, FolderCog } from 'lucide-svelte'
  // is transformed to
  import User from 'lucide-svelte/icons/user';
  import FolderCog from 'lucide-svelte/icons/folder-cog'
</script>

<User />
<FolderCog />
```

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by david-plugge** [comment]
I have not checked out if other packages than `lucide-svelte` expose the icons via the `.../icons/*` path but if so it would work for any lucide package when used with vite

**Comment by ericfennis** [comment]
@david-plugge This is awesome thanks for sharing.

Aliases could be a problem, but not in the way you described. We currently have alias imports for certain icons, sometimes we rename icons when needed, we solve this by exporting the "old" name. But I think we can fix this.

**Comment by TheEisbaer** [comment]
@david-plugge  thank you so much, this has solved my problem over at tabler icons:

```typescript
function tablerSvelteImportOptimizer(): import('vite').Plugin {
	return {
		name: 'tabler-svelte optimizer',
		transform(code, id) {
			const ms = new MagicString(code, { filename: id });
			ms.replace(
				/([ \t]*)import\s+\{([^;]*?)\}\s+from\s+['"]@tabler\/icons-svelte['"];/g,
				(match, whitespace: string, importNames: string) => {
					const hasSemi = match.endsWith(';');
					const imports = importNames
						.split(',')
						.map((v) => v.trim())
						.map((name) => {
							const path = name;
							return `${whitespace}import ${name} from '@tabler/icons-svelte/${path}.svelte'${hasSemi ? ';' : ''}`;
						});
					return imports.join('\n');
				}
			);

			if (ms.hasChanged()) {
				return {
					code: ms.toString(),
					map: ms.generateMap()
				};
			}
		}
	};
}
```

**Comment by jamesbirtles** [comment]
cool plugin, I had to modify it a bit to get it to work with icons with numbers in them, as well as new lines within the import.
Whilst i was there I also bodged in support for lucide aliases by checking against the .d.ts for each icon, I'm sure this pretty inefficient but its still faster than transforming all the icons 

```ts
function lucideSvelteImportOptimizer(): Plugin {
	const aliases = readFileSync('node_modules/lucide-svelte/dist/aliases.d.ts', 'utf8');
	return {
		name: 'lucide-svelte optimizer',
		transform(code, id) {
			const ms = new MagicString(code, { filename: id });

			ms.replace(
				/([ \t]*)import\s+\{([^}]+)\}\s+from\s+["']lucide-svelte["'];/g,
				(match, whitespace: string, importNames: string) => {
					const hasSemi = match.endsWith(';');

					const imports = importNames
						.split(',')
						.map((v) => v.trim())
						.map((name) => {
							let path;
							const alias = aliases.match(
								new RegExp(`as ${name} } from '\\.\\/icons\\/(.+)\\.svelte';`),
							);
							if (alias) {
								path = alias[1]!;
							} else {
								path = name
									.split('')
									.map((c, i) => {
										const code = c.charCodeAt(0);
										return (code >= 65 && code <= 90) || (code >= 48 && code <= 57)
											? (i === 0 ? '' : '-') + c.toLowerCase()
											: c;
									})
									.join('');
							}

							return `${whitespace}import ${name} from 'lucide-svelte/icons/${path}'${hasSemi ? ';' : ''}`;
						});

					return imports.join('\n');
				},
			);

			if (ms.hasChanged()) {
				return {
					code: ms.toString(),
					map: ms.generateMap(),
				};
			}
		},
	};
}
```

**Comment by jguddas** [comment]
Maybe someone wants to try https://www.npmjs.com/package/vite-plugin-barrel

**Comment by corentingosselin** [comment]
get it works, for lucide-react, thank you for the script: 
``` 
import { Plugin } from 'vite';
import MagicString from 'magic-string';

function lucideReactImportOptimizer(): Plugin {
  return {
    name: 'lucide-react-import-optimizer',
    transform(code: string, id: string) {
      const ms = new MagicString(code, { filename: id });

      ms.replace(
        /import\s+\{\s*([^}]+)\s*\}\s+from\s+['"]lucide-react['"]/g,
        (match: string, imports: string) => {
          const importStatements = imports
            .split(',')
            .map((imp: string) => {
              const [name, alias] = imp.split(' as ').map((s: string) => s.trim());
              const importName = alias || name;
              const kebabCaseName = name
                .replace(/([a-z])([A-Z])/g, '$1-$2')
                .toLowerCase();
              return `import ${importName} from 'lucide-react/dist/esm/icons/${kebabCaseName}';`;
            })
            .join('\n');
          return importStatements;
        }
      );

      if (ms.hasChanged()) {
        return {
          code: ms.toString(),
          map: ms.generateMap(),
        };
      }
    },
  };
}

export default lucideReactImportOptimizer;

```

**Comment by WarningImHack3r** [comment]
Hi all, I made a proper Vite preprocessor for that purpose: https://github.com/WarningImHack3r/vite-plugin-lucide-preprocess.
Been using it for 3 months, includes an auto-updater and is thoroughly tested. Check it out!

**Comment by corentingosselin** [comment]
> Hi all, I made a proper Vite preprocessor for that purpose: https://github.com/WarningImHack3r/vite-plugin-lucide-preprocess. Been using it for 3 months, includes an auto-updater and is thoroughly tested. Check it out!

does not load using vite.config.ts
```/// <reference types='vitest' />
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import { nxCopyAssetsPlugin } from '@nx/vite/plugins/nx-copy-assets.plugin';
import lucidePreprocess from "vite-plugin-lucide-preprocess";

export default defineConfig({
  root: __dirname,
  cacheDir: '../../node_modules/.vite/apps/mobile-app',
  server: {
    port: 4000,
    host: 'localhost',
  },
  preview: {
    port: 4300,
    host: 'localhost',
  },
  plugins: [
    react(),
    nxViteTsPaths(),
    nxCopyAssetsPlugin(['*.md']),
    lucidePreprocess(),
  ],
  build: {
    outDir: '../../dist/apps/mobile-app',
    emptyOutDir: true,
    reportCompressedSize: true,
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
  test: {
    watch: false,
    globals: true,
    environment: 'jsdom',
    include: ['src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    reporters: ['default'],
    coverage: {
      reportsDirectory: '../../coverage/apps/mobile-app',
      provider: 'v8',
    },
  },
});``` 

```      An error occurred while processing files for the @nx/vite/plugin plugin.
    - apps/backoffice/vite.config.ts: Build failed with 1 error:
  node_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] "vite-plugin-lucide-preprocess" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vite.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
      Error: Build failed with 1 error:
      node_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] "vite-plugin-lucide-preprocess" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vite.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.```

**Comment by WarningImHack3r** [comment]
>       Error: Build failed with 1 error:
>       node_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] "vite-plugin-lucide-preprocess" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vite.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
> ```

My plugin is ESM only, try using a `vite.config.mts` to force ESM

**Comment by WarningImHack3r** [comment]
> for lucid-react the import path is: lucide-react/dist/esm/icons/

Good to know! Can you please open an issue?

**Comment by enyo** [comment]
@ericfennis I think that the DX could be drastically improved, without the need for such vite plugin optimizations, if the icons would be exported properly. Right now this is the generated file:

```js
export { default } from "./triangle-alert.svelte";
```

I _think_ that if that would be changed to:

```js
import { default: TriangleAlert } from "./triangle-alert.svelte";
export default TriangleAlert;
```

then we would get autocomplete for the direct import.

**Comment by jguddas** [comment]
> @ericfennis I think that the DX could be drastically improved, without the need for such vite plugin optimizations, if the icons would be exported properly. Right now this is the generated file:
> 
> ```js
> export { default } from "./triangle-alert.svelte";
> ```
> 
> I _think_ that if that would be changed to:
> 
> ```js
> import { default: TriangleAlert } from "./triangle-alert.svelte";
> export default TriangleAlert;
> ```
> 
> then we would get autocomplete for the direct import.

If by 'Better DX' you mean that it would improve performance, I would be happily surprised to see that actually work.

The problem as I see it is that vite currently doesn't perform barrel optimization in dev mode.

NEXT is the only thing that I know that comes with this kind of barrel optimization out of the box.

**Comment by david-plugge** [comment]
this should also work
```ts
import TriangleAlert from "./triangle-alert.svelte";
export default TriangleAlert;
```

> If by 'Better DX' you mean that it would improve performance, I would be happily surprised to see that actually work.

No, he is just talking about auto-completion. If you just `export { default } from "./triangle-alert.svelte";` the ts-server does not know the name of the default export and therefore does not suggest it when typing `TriangleAle...`. If you name the default export it does.

**Comment by corentingosselin** [comment]
It seems the new lucide-react version has fixed this issue, you can now remove any script + you have a new great dynamic import: https://github.com/lucide-icons/lucide/releases/tag/0.471.0

**Comment by WarningImHack3r** [comment]
> It seems […] you can now remove any script + you have a new great dynamic import […]

To me this does not solve any of the static imports tree shaking issues, it’s just a more granular but more expensive dynamic icons component

Even if it was, if it’s only for React 19 it shrinks a lot the amount of people impacted by this change (among all the Lucide + Vite users)

**Comment by corentingosselin** [comment]
> > It seems […] you can now remove any script + you have a new great dynamic import […]
> 
> To me this does not solve any of the static imports tree shaking issues, it’s just a more granular but more expensive dynamic icons component
> 
> Even if it was, if it’s only for React 19 it shrinks a lot the amount of people impacted by this change (among all the Lucide + Vite users)

I also do not have the issue with static import, but you are right it does not impact everyone

**Comment by burgil** [comment]
`vite.config.ts`:

I finally solved it with the `vite-plugin-barrel`: _(It no longer loads 1600 files on load, just the 60 I need and icons still works)_

Note: if you're using swc there's some extra steps [here](https://www.npmjs.com/package/vite-plugin-barrel)

```ts
import { defineConfig } from 'vite'
import { barrel } from 'vite-plugin-barrel'
export default defineConfig({
  plugins: [
    react(),
    barrel({
      packages: ['lucide-react']
    }),
    tsconfigPaths(),
  ]
});
```

Make sure you __remove__ any optimizeDeps for lucide-react, this prevented it from working:

```ts
  // This tells Vite which dependencies to pre-build in dev mode.
  optimizeDeps: {
    // Put problematic deps that break bundling here, mostly those with binaries.
    // For example ['better-sqlite3'] if you use that in server functions.
    // exclude: ['lucide-react'], // Don't do that
  },
```

**Comment by hgoona** [comment]
> > It seems […] you can now remove any script + you have a new great dynamic import […]
> 
> To me this does not solve any of the static imports tree shaking issues, it’s just a more granular but more expensive dynamic icons component
> 
> Even if it was, if it’s only for React 19 it shrinks a lot the amount of people impacted by this change (among all the Lucide + Vite users)

I've just arrived at these threads after trying to solve my poor DX in SvelteKit and Lucide-svelte icons. @WarningImHack3r Is your plugin the preferred solution at present? (for SvelteKit +lucide-svelte devolpers) ?

**Comment by WarningImHack3r** [comment]
@hgoona to be completely fair it seems to not be the _only_ solution but my plugin works well (and I use it myself in your situation)

**Comment by hgoona** [comment]
@WarningImHack3r I started using the plugin and it works on my machine however with the exact project we're getting an error with the shadcn-svelte dropdown component imported as `import * as DropdownMenu from "./ui/dropdown-menu";` 

Do you know what the issue might be? Or if i should use another solution (which one??)

EDIT: after upgrading to the latest dropdown component using: `bun x shadcn-svelte@next add dropdown-menu` 
I am now seeing this same error my partner sees:
```
7:07:20 pm [vite] (ssr) page reload tailwind.config.js (x2)
NEWLUCIA__getProfile_setLocals▶
NEWLUCIA__getProfile_setLocals▶
7:07:21 pm [vite] (ssr) Error when evaluating SSR module /src/routes/(app)/+layout.svelte: Cannot read properties of undefined (reading 'Sub') 
      at D:\CODE\My_App_V2\src\lib\components\ui\dropdown-menu\index.ts:13:35
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async ESModulesEvaluator.runInlinedModule (file:///D:/CODE/My_App_V2/node_modules/vite/dist/node/module-runner.js:1049:5)        
      at async SSRCompatModuleRunner.directRequest (file:///D:/CODE/My_App_V2/node_modules/vite/dist/node/module-runner.js:1271:61)       
      at async SSRCompatModuleRunner.directRequest (file:///D:/CODE/My_App_V2/node_modules/vite/dist/node/chunks/dep-CfG9u7Cn.js:30895:23)
      at async SSRCompatModuleRunner.cachedRequest (file:///D:/CODE/My_App_V2/node_modules/vite/dist/node/module-runner.js:1167:76)       
      at async eval (D:/CODE/My_App_V2/src/lib/components/Nav.svelte:3:947)
      at async ESModulesEvaluator.runInlinedModule (file:///D:/CODE/My_App_V2/node_modules/vite/dist/node/module-runner.js:1049:5)
      at async SSRCompatModuleRunner.directRequest (file:///D:/CODE/My_App_V2/node_modules/vite/dist/node/module-runner.js:1271:61)
      at async SSRCompatModuleRunner.directRequest (file:///D:/CODE/My_App_V2/node_modules/vite/dist/node/chunks/dep-CfG9u7Cn.js:30895:23)
TypeError: Cannot read properties of undefined (reading 'Sub')
    at D:\CODE\My_App_V2\src\lib\components\ui\dropdown-menu\index.ts:13:35
7:08:42 pm [vite] (ssr) page reload src/lib/components/Nav.svelte
```

**Comment by WarningImHack3r** [comment]
@hgoona can you please open an issue on my repo? It'll avoid cluttering this issue with unrelated stuff

**Comment by Johann-Goncalves-Pereira** [comment]
Ok, I was having the same problem. It took me a lot of time to notice that the problem was not related to my code, but with `lucide`.

Then after searching online I found this post, [Slow page loading due to Lucide load all icons in dev mode](https://github.com/lucide-icons/lucide/issues/2583) in there a collaborator send me to this post [Vite plugin for optimization](https://github.com/lucide-icons/lucide/issues/1944).

Obviously, there was no solution for my case in specific ([lucide-astro](https://github.com/dzeiocom/lucide-astro)), so I made one. 

<details>
<summary>Code for plugin <code>./lucide.config.ts</code></summary>

My code is more robust than the that @david-plugge made. I try to not use third parties like `magic-string`, just because.
Because it was Astro, Vite is under the hood. So created the types for them. I tried to make the code more readable, with separation of concerns and strongly typed.

```ts

// Pre-compile regex for better performance
const LUCIDE_IMPORT_PATTERN =
  /([ \t]*)import\s+\{\s*([^}]+)\s*\}\s+from\s+['"]lucide-astro['"]/g;

/**
 * SourceMap interface for transformation output
 */
interface SourceMap {
  version: number;
  sources: string[];
  names: string[];
  sourceRoot?: string;
  sourcesContent?: string[];
  mappings: string;
  file: string;
}

/**
 * Plugin interface matching Vite/Rollup plugin structure
 */
interface AstroPlugin {
  name: string;
  transform: (code: string, id: string) => TransformResult | null | undefined;
}

/**
 * Result of the transform operation
 */
interface TransformResult {
  code: string;
  map?: SourceMap | null;
}

/**
 * Creates a Vite/Astro plugin that optimizes lucide-astro imports by converting
 * destructured imports to direct imports for better tree-shaking
 *
 * @returns An Astro plugin that transforms lucide-astro imports
 */
function createLucideAstroImportOptimizer(): AstroPlugin {
  return {
    name: "lucide-astro-optimizer",
    transform(sourceCode: string, filePath: string): TransformResult | null | undefined {
      if (!isValidInput(sourceCode, filePath)) return null;
      
      try {
        // Quick check if the file contains lucide-astro imports
        if (!sourceCode.includes("lucide-astro")) return null;

        const { transformedCode, hasChanges } = transformLucideImports(sourceCode);
        
        if (hasChanges) {
          return {
            code: transformedCode,
            map: null, // No source maps in this implementation
          };
        }

        return null;
      } catch (error) {
        handleTransformError(error);
        return null;
      }
    },
  };
}

/**
 * Validates the input parameters for processing
 */
function isValidInput(code: string, id: string): boolean {
  return Boolean(code && id);
}

/**
 * Transforms lucide-astro imports from destructured to individual imports
 */
function transformLucideImports(sourceCode: string): { transformedCode: string; hasChanges: boolean } {
  let hasChanges = false;
  
  const transformedCode = sourceCode.replace(
    LUCIDE_IMPORT_PATTERN,
    (match: string, indentation: string, importNames: string): string => {
      if (!importNames.trim()) return match;

      const semicolonAtEnd = match.endsWith(";");
      const individualImports = convertToIndividualImports(importNames, indentation, semicolonAtEnd);

      if (individualImports) {
        hasChanges = true;
        return individualImports;
      }

      return match;
    }
  );

  return { transformedCode, hasChanges };
}

/**
 * Converts a comma-separated list of imports to individual import statements
 */
function convertToIndividualImports(
  importNames: string, 
  indentation: string, 
  withSemicolon: boolean
): string {
  return importNames
    .split(",")
    .map((name) => name.trim())
    .filter(Boolean)
    .map((name) => {
      const kebabCasePath = convertToKebabCase(name);
      const semicolon = withSemicolon ? ";" : "";
      return `${indentation}import ${name} from 'lucide-astro/${kebabCasePath}'${semicolon}`;
    })
    .join("\n");
}

/**
 * Converts a camelCase or PascalCase string to kebab-case
 */
function convertToKebabCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/([a-z])([A-Z])/g, "$1-$2");
}

/**
 * Handles and logs transformation errors
 */
function handleTransformError(error: unknown): void {
  const typedError = error instanceof Error ? error : new Error(String(error));
  console.error("Error in lucide-astro-optimizer plugin:", typedError);
}

export default createLucideAstroImportOptimizer;

```

</details>

<details>
<summary>Code for Astro <code>./lastro.config.mjs</code></summary>

```mjs

// @ts-check
import { defineConfig } from "astro/config";
import lucideAstroImportOptimizer from "./lucide.config";

// https://astro.build/config
export default defineConfig({
  vite: {
    plugins: [lucideAstroImportOptimizer()],
  },
});

```

</details>



_Obs:. I don't know how to make a plugin package for vite or how I could make a PR in this package to implement this + my difficulty is solved. If any one want's to use this code use as you see fit, but please give me credit if possible. It would help my career if I made so open-source contributions._

**Comment by byronwall** [comment]
I was able to get `lucide-solid` to avoid loading everything on refresh using the config below.  Note that this is inside `app.config.ts` since I am running through Solid Start.

Many thanks @WarningImHack3r for the plugin. I attempted to use `vite-plugin-barrel` but it did not resolve the "load everything" problem.  `vite-plugin-lucide-preprocess` was a drop-in solution.

```
import { defineConfig } from "@solidjs/start/config";
import tsconfigPaths from "vite-tsconfig-paths";
import lucidePreprocess from "vite-plugin-lucide-preprocess";

export default defineConfig({
  vite: {
    plugins: [lucidePreprocess(), tsconfigPaths()],
    optimizeDeps: {},
  },
});

```

```
{
  "name": "example-bare",
  "type": "module",
  "scripts": {
    "prepare": "panda codegen",
    "dev": "vinxi dev",
    "build": "vinxi build",
    "start": "vinxi start"
  },
  "dependencies": {
    "@ark-ui/solid": "^5.30.0",
    "@solidjs/start": "^1.1.0",
    "lucide-solid": "^0.562.0",
    "solid-js": "^1.9.5",
    "vinxi": "^0.5.7"
  },
  "engines": {
    "node": ">=22"
  },
  "devDependencies": {
    "@pandacss/dev": "^1.7.2",
    "vite-plugin-lucide-preprocess": "^1.4.6",
    "vite-tsconfig-paths": "^6.0.3"
  }
}
```
