### ISSUE TITLE
Unable to develop site on Node 18 and up

### ISSUE THREAD

**Issue by wojtekmaj** [lucide-icons/lucide#842]
On `pnpm dev`:

```
error - src/lib/fetchAllContributors.ts (114:10) @ getContributors
error - Error: Error: error:0308010C:digital envelope routines::unsupported
    at getContributors (webpack-internal:///./src/lib/fetchAllContributors.ts:89:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getData (webpack-internal:///./src/lib/icons.tsx:32:26)
    at async Promise.all (index 0)
    at async getStaticProps (webpack-internal:///./src/pages/index.tsx:75:18)
    at async Object.renderToHTML (/Users/wojciech.maj/Projekty/lucide/node_modules/.pnpm/next@12.2.5_q6el6r4hbd2fftzckrwpdnyobi/node_modules/next/dist/server/render.js:368:20)
    at async doRender (/Users/wojciech.maj/Projekty/lucide/node_modules/.pnpm/next@12.2.5_q6el6r4hbd2fftzckrwpdnyobi/node_modules/next/dist/server/base-server.js:908:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/Users/wojciech.maj/Projekty/lucide/node_modules/.pnpm/next@12.2.5_q6el6r4hbd2fftzckrwpdnyobi/node_modules/next/dist/server/base-server.js:1013:28)
    at async /Users/wojciech.maj/Projekty/lucide/node_modules/.pnpm/next@12.2.5_q6el6r4hbd2fftzckrwpdnyobi/node_modules/next/dist/server/response-cache.js:69:36 {
  page: '/'
}
```

**Comment by wojtekmaj** [comment]
Related: https://github.com/vercel/next.js/issues/30078
